<a href="https://colab.research.google.com/github/11AJ/Machine-Learning/blob/main/Diabetes_1Stop_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
df=pd.read_csv('/content/Diabities-210331-154610.csv')

In [17]:
df.head()

Unnamed: 0  Pregnancies  Glucose  ...  DiabetesPedigreeFunction   Age  Outcome
0         NaN          6.0    148.0  ...                     0.627  50.0      1.0
1         NaN          1.0     85.0  ...                     0.351  31.0      0.0
2         NaN          8.0    183.0  ...                     0.672  32.0      1.0
3         NaN          1.0     89.0  ...                     0.167  21.0      0.0
4         NaN          0.0    137.0  ...                     2.288  33.0      1.0

[5 rows x 10 columns]

In [18]:
df['Insulin'].replace(0.0,df['Insulin'].mean(),inplace=True)
df['skin thickness'].replace(0.0,df['skin thickness'].mean(),inplace=True)

In [19]:
df.head()

Unnamed: 0  Pregnancies  Glucose  ...  DiabetesPedigreeFunction   Age  Outcome
0         NaN          6.0    148.0  ...                     0.627  50.0      1.0
1         NaN          1.0     85.0  ...                     0.351  31.0      0.0
2         NaN          8.0    183.0  ...                     0.672  32.0      1.0
3         NaN          1.0     89.0  ...                     0.167  21.0      0.0
4         NaN          0.0    137.0  ...                     2.288  33.0      1.0

[5 rows x 10 columns]

In [22]:
df.isnull().sum()

Unnamed: 0                  769
Pregnancies                   1
Glucose                       1
blood pressure                1
skin thickness                1
Insulin                       1
BMI                           1
DiabetesPedigreeFunction      1
Age                           1
Outcome                       1
dtype: int64

In [23]:
df.tail()

Unnamed: 0  Pregnancies  Glucose  ...  DiabetesPedigreeFunction   Age  Outcome
764         NaN          2.0    122.0  ...                     0.340  27.0      0.0
765         NaN          5.0    121.0  ...                     0.245  30.0      0.0
766         NaN          1.0    126.0  ...                     0.349  47.0      1.0
767         NaN          1.0     93.0  ...                     0.315  23.0      0.0
768         NaN          NaN      NaN  ...                       NaN   NaN      NaN

[5 rows x 10 columns]

In [30]:
df=df.iloc[:-1,:]

In [31]:
df.isnull().sum()

Unnamed: 0                  768
Pregnancies                   0
Glucose                       0
blood pressure                0
skin thickness                0
Insulin                       0
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [32]:
df.head()

Unnamed: 0  Pregnancies  Glucose  ...  DiabetesPedigreeFunction   Age  Outcome
0         NaN          6.0    148.0  ...                     0.627  50.0      1.0
1         NaN          1.0     85.0  ...                     0.351  31.0      0.0
2         NaN          8.0    183.0  ...                     0.672  32.0      1.0
3         NaN          1.0     89.0  ...                     0.167  21.0      0.0
4         NaN          0.0    137.0  ...                     2.288  33.0      1.0

[5 rows x 10 columns]

In [33]:
x=df.iloc[:,1:-1]
y=df.iloc[:,-1]

In [37]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [42]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(576, 8)
(576,)
(192, 8)
(192,)


In [43]:
from sklearn.ensemble import RandomForestClassifier

In [110]:
mod=RandomForestClassifier(n_estimators=250,max_depth=10,min_samples_split=10)

In [111]:
mod.fit(x_train,y_train)

RandomForestClassifier(max_depth=10, min_samples_split=10, n_estimators=250)

In [112]:
print(mod.score(x_train,y_train))
print(mod.score(x_test,y_test))

0.9340277777777778
0.96875


In [113]:
y_pred=mod.predict(x_test)

In [114]:
y_pred[:5]

array([1., 1., 0., 1., 0.])

In [115]:
y_test[:5]

array([1., 1., 0., 1., 0.])

In [116]:
from sklearn.metrics import classification_report,confusion_matrix

In [117]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[126   1]
 [  5  60]]
              precision    recall  f1-score   support

         0.0       0.96      0.99      0.98       127
         1.0       0.98      0.92      0.95        65

    accuracy                           0.97       192
   macro avg       0.97      0.96      0.96       192
weighted avg       0.97      0.97      0.97       192

