<a href="https://colab.research.google.com/github/11AJ/Machine-Learning/blob/main/flowers_classfication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('/content/iris_csv-210120-132620.csv')

In [4]:
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [5]:
df.isnull().sum()

sepallength    0
sepalwidth     0
petallength    0
petalwidth     0
class          0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [8]:
df['class']=le.fit_transform(df['class'])

In [9]:
df['class'].value_counts()

2    50
1    50
0    50
Name: class, dtype: int64

In [10]:
df.head()

sepallength  sepalwidth  petallength  petalwidth  class
0          5.1         3.5          1.4         0.2      0
1          4.9         3.0          1.4         0.2      0
2          4.7         3.2          1.3         0.2      0
3          4.6         3.1          1.5         0.2      0
4          5.0         3.6          1.4         0.2      0

In [11]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [13]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [14]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
mod=RandomForestClassifier(n_estimators=200,max_depth=10,min_samples_split=15)

In [17]:
mod.fit(x_train,y_train)

RandomForestClassifier(max_depth=10, min_samples_split=15, n_estimators=200)

In [18]:
print(mod.score(x_train,y_train))
print(mod.score(x_test,y_test))

0.9833333333333333
0.9333333333333333


In [19]:
y_pred=mod.predict(x_test)

In [25]:
y_test[:5]

72     1
119    2
48     0
78     1
23     0
Name: class, dtype: int64

In [27]:
y_pred[:5]

array([1, 1, 0, 1, 0])

In [28]:
from sklearn.metrics import confusion_matrix,classification_report

In [29]:
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[ 9  0  0]
 [ 0  7  1]
 [ 0  1 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.88      0.88      0.88         8
           2       0.92      0.92      0.92        13

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

