<a href="https://colab.research.google.com/github/11AJ/Machine-Learning/blob/main/Product_quality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [197]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Reading CSV

In [198]:
df = pd.read_csv('/content/product_quality.csv')

In [199]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

Checking for Null values

In [200]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             3
residual sugar          0
chlorides               6
free sulfur dioxide     0
total sulfur dioxide    0
density                 3
pH                      1
sulphates               1
alcohol                 0
quality                 0
dtype: int64

In [201]:
df['citric acid'].fillna(df['citric acid'].mean(),inplace=True)

In [202]:
df['chlorides'].fillna(df['chlorides'].mean(),inplace=True)
df['density'].fillna(df['density'].mean(),inplace=True)
df['pH'].fillna(df['pH'].mean(),inplace=True)
df['sulphates'].fillna(df['sulphates'].mean(),inplace=True)

In [203]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [204]:
df.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

In [205]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [206]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.271178        2.538806   
std         1.741096          0.179060     0.194722        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087517            15.874922             46.467792     0.996752   
std       0.047055            10.460157             32.895324     0.001883   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.310957     0.658185    10.422983     5.636023  
std       0.154261     0.169501     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [207]:
from sklearn import preprocessing

 MIN MAX SCALER

In [208]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))

In [209]:
df['free sulfur dioxide'] = min_max_scaler.fit_transform(x)
df['total sulfur dioxide'] = min_max_scaler.fit_transform(x)
df['fixed acidity'] = min_max_scaler.fit_transform(x)
df['residual sugar'] = min_max_scaler.fit_transform(x)
df['pH'] = min_max_scaler.fit_transform(x)
df['alcohol'] = min_max_scaler.fit_transform(x)

In [210]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        0.279329          0.527821     0.271178        0.279329   
std         0.122644          0.179060     0.194722        0.122644   
min         0.000000          0.120000     0.000000        0.000000   
25%         0.184932          0.390000     0.090000        0.184932   
50%         0.273973          0.520000     0.260000        0.273973   
75%         0.356164          0.640000     0.420000        0.356164   
max         1.000000          1.580000     1.000000        1.000000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087517             0.279329              0.279329     0.996752   
std       0.047055             0.122644              0.122644     0.001883   
min       0.012000             0.000000              0.000000     0.990070   
25%       0.070000             0.184932              0.184932     0.995600   
50%       0.079000             0.273973              0.273973     0.996750   
75%       0.090000             0.356164              0.356164     0.997835   
max       0.611000             1.000000              1.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      0.279329     0.658185     0.279329     5.636023  
std       0.122644     0.169501     0.122644     0.807569  
min       0.000000     0.330000     0.000000     3.000000  
25%       0.184932     0.550000     0.184932     5.000000  
50%       0.273973     0.620000     0.273973     6.000000  
75%       0.356164     0.730000     0.356164     6.000000  
max       1.000000     2.000000     1.000000     8.000000

In [211]:
df.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.397260              0.70         0.00        0.397260      0.076   
1       0.520548              0.88         0.00        0.520548      0.098   
2       0.438356              0.76         0.04        0.438356      0.092   
3       0.109589              0.28         0.56        0.109589      0.075   
4       0.397260              0.70         0.00        0.397260      0.076   
5       0.369863              0.66         0.00        0.369863      0.075   
6       0.328767              0.60         0.06        0.328767      0.069   
7       0.363014              0.65         0.00        0.363014      0.065   
8       0.315068              0.58         0.02        0.315068      0.073   
9       0.260274              0.50         0.36        0.260274      0.071   

   free sulfur dioxide  total sulfur dioxide  density        pH  sulphates  \
0             0.397260              0.397260   0.9978  0.397260       0.56   
1             0.520548              0.520548   0.9968  0.520548       0.68   
2             0.438356              0.438356   0.9970  0.438356       0.65   
3             0.109589              0.109589   0.9980  0.109589       0.58   
4             0.397260              0.397260   0.9978  0.397260       0.56   
5             0.369863              0.369863   0.9978  0.369863       0.56   
6             0.328767              0.328767   0.9964  0.328767       0.46   
7             0.363014              0.363014   0.9946  0.363014       0.47   
8             0.315068              0.315068   0.9968  0.315068       0.57   
9             0.260274              0.260274   0.9978  0.260274       0.80   

    alcohol  quality  
0  0.397260        5  
1  0.520548        5  
2  0.438356        5  
3  0.109589        6  
4  0.397260        5  
5  0.369863        5  
6  0.328767        5  
7  0.363014        7  
8  0.315068        7  
9  0.260274        5

Splitting Dataset

In [212]:
x=df.iloc[:,1:-1]
y=df.iloc[:,-1]

In [213]:
from sklearn.model_selection import train_test_split

In [214]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

In [215]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1199, 10)
(1199,)
(400, 10)
(400,)


Applying DecisionTree Classifier

In [216]:
from sklearn.tree import DecisionTreeClassifier

In [298]:
dt_model=DecisionTreeClassifier(criterion='gini',min_samples_split=10,max_depth=40)

In [299]:
dt_model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=40, min_samples_split=10)

In [300]:
dt_model.score(x_train,y_train)

0.8315262718932444

In [301]:
dt_model.score(x_test,y_test)

0.615

In [302]:
dt_pred = dt_model.predict(x_test)

In [303]:
dt_pred[0:5]

array([5, 4, 6, 7, 5])

In [304]:
from sklearn.metrics import confusion_matrix,classification_report

In [305]:
print(confusion_matrix(y_test,dt_pred))

[[  0   0   0   1   0   0]
 [  1   2   6   4   0   0]
 [  0   6 128  41   3   0]
 [  0   4  36  99  13   0]
 [  0   0  10  26  17   1]
 [  0   0   0   0   2   0]]


In [306]:
print(classification_report(y_test,dt_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.17      0.15      0.16        13
           5       0.71      0.72      0.72       178
           6       0.58      0.65      0.61       152
           7       0.49      0.31      0.38        54
           8       0.00      0.00      0.00         2

    accuracy                           0.61       400
   macro avg       0.32      0.31      0.31       400
weighted avg       0.61      0.61      0.61       400



**Applying Random Forest**

In [226]:
from sklearn.ensemble import RandomForestClassifier

In [334]:
mod=RandomForestClassifier(n_estimators=100,max_depth=20,min_samples_split=10)

In [335]:
mod.fit(x_train,y_train)

RandomForestClassifier(max_depth=20, min_samples_split=10)

In [336]:
print(mod.score(x_train,y_train))
print(mod.score(x_test,y_test))

0.8832360300250208
0.6125


In [337]:
rf_pred=mod.predict(x_test)

In [338]:
rf_pred[:5]

array([6, 5, 6, 7, 5])

In [339]:
y_test[:5]

1133    7
72      5
272     5
1007    7
694     5
Name: quality, dtype: int64

In [340]:
print(confusion_matrix(y_test,rf_pred))

[[  0   0   0   1   0   0]
 [  0   0  10   3   0   0]
 [  0   0 124  52   2   0]
 [  0   0  38 108   6   0]
 [  0   0   7  34  13   0]
 [  0   0   0   1   1   0]]


In [341]:
print(classification_report(y_test,rf_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        13
           5       0.69      0.70      0.69       178
           6       0.54      0.71      0.62       152
           7       0.59      0.24      0.34        54
           8       0.00      0.00      0.00         2

    accuracy                           0.61       400
   macro avg       0.30      0.27      0.28       400
weighted avg       0.59      0.61      0.59       400



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Applying Logistic Regression**

In [342]:
from sklearn.linear_model import LogisticRegression

In [343]:
model=LogisticRegression()

In [344]:
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [345]:
lr_pred=model.predict(x_test)

In [346]:
print(model.score(x_train,y_train))
print(model.score(x_test,y_test))

0.5221017514595496
0.525


In [347]:
lr_pred[0:5]

array([6, 5, 6, 6, 6])

In [348]:
print(confusion_matrix(y_test,lr_pred))

[[  0   0   1   0   0   0]
 [  0   0  10   2   1   0]
 [  0   0 113  62   3   0]
 [  0   0  55  95   2   0]
 [  0   0   9  43   2   0]
 [  0   0   0   2   0   0]]


In [349]:
print(classification_report(lr_pred,y_test))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.63      0.60      0.62       188
           6       0.62      0.47      0.53       204
           7       0.04      0.25      0.06         8
           8       0.00      0.00      0.00         0

    accuracy                           0.53       400
   macro avg       0.22      0.22      0.20       400
weighted avg       0.62      0.53      0.56       400



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
